### ISSUE TITLE
evaluate test-harness tooling to confirm that the choices are appropriate

### ISSUE THREAD

**Issue by jgravois** [terraformer-js/terraformer#7]
the tooling in this repo is basically just an update and monorepo port of what @patrickarlt used in https://github.com/Esri/arcgis-to-geojson-utils

### (1) is there any reason _not_ to use `tape`?

my impression is that we've tacked on jasmine and karma and everything else in other JS libraries i've contributed to mostly just to mock internet requests. i _think_ `tape` is sufficient for the unit tests we need to run here, right?

### (2) can/should the browserify dependency be removed?

at this point we could probably test the native ES modules directly in the browser. should we though?

### (2a) are any of the other dependencies already 'stale' or out of fashion?

i've never cared much about popularity contests, but lots of the work i've done maintaining terraformer and other libraries over the last couple years has been trying to stay ahead of security vulnerabilities and keep things running in newer versions of Node.js as they've come out. in that sense, antiquated architecture is a pain.

**Comment by patrickarlt** [comment]
> (1) is there any reason not to use tape?

Not really, I really like the simplicity of `tape` when I don't need all the features of `karam` + `jasmine`. That said if `tape` is stale I REALLY like `ava` for testing Node only stuff, which I what I use on Acetate.

> (2) can/should the browserify dependency be removed?

Sounds good to me. Not sure how that would work with the rest of the testing stack but if this issue is about switching to a different test stack to reduce maintenance then go for it.

> (2a) are any of the other dependencies already 'stale' or out of fashion?

As far as I can see no.

**Comment by jgravois** [comment]
thank you @patrickarlt!
