### ISSUE TITLE
Is there any replacement for Terraformer Core and Geostore?

### ISSUE THREAD

**Issue by wondie** [terraformer-js/terraformer#70]
Is there any replacement for Terraformer Code and Geostore in this repository?
https://github.com/Esri/terraformer/blob/master/docs/core.md
https://github.com/Esri/terraformer-geostore

**Comment by jgravois** [comment]
there is not, nor am i planning on it.

**Comment by wondie** [comment]
So it means I have to use another library?

**Comment by jgravois** [comment]
> Do you know of any good replacement libraries?

the primitives [that you linked to](https://github.com/Esri/terraformer/blob/master/docs/core.md) that are present in Esri/terraformer and missing here are purely a convenience wrapper. if you can live without them, you can use the libraries here. if you can't, use https://github.com/Esri/terraformer.

since the geostore code wasn't ported here, if you're interested in it you should just use the code in https://github.com/Esri/terraformer-geostore

i doubt you're the only one who has had this question so i added another item to the FAQ to try and help other folks in the future. https://github.com/terraformer-js/terraformer/commit/2b466bb3bdeac65c3cb7474062220fa7c80d9dcc

**Comment by wondie** [comment]
@jgravois Thank you so much for the clarification!
